on: [push]
name: ci
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.15"]
    steps:
      - name: Install Go v${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: go build

      - name: Test
        run: go test
